---
# <font color="#CA3532">Deep Learning Fundamentals and Basic Tools (2026/2027) - Lab Assignment 2</font>
---


* This assignment is centered on the use of [Keras](https://keras.io/).

* Keras is an open-source deep learning library designed to make the development and experimentation of neural networks simple, fast, and intuitive. It provides a user-friendly, modular, and extensible interface.

* Keras can run on top of different computational backends. In this assignment, we will use **TensorFlow** as the backend.

* Throughout the assignment, we will see how easily neural networks can be created with Keras and explore some of the many configuration options available, including network architecture, activation functions, optimizers, and regularization techniques.

### <font color="#CA3532">Instructions</font>

Before You Start the Project

It is strongly recommended that you first clone the entire repository using the following command and read the [`README.md`](https://github.com/samanemami/DLFBT-LAB/blob/main/README.md) file before starting the project.

!git clone https://github.com/samanemami/DLFBT-LAB.git


Keep `lab2_2026.ipynb` and `dlfbt_lab2.py` in the same directory.

### <font color="#CA3532">Imports and reproducibility</font>

In [6]:
import os
import sys
import importlib
import numpy as np
from pathlib import Path


sys.path.append("../")

import config

solution = importlib.import_module(config.get_source_module(lab_number=1))
solution.set_reproducible(42)

print("Loaded:", Path(solution.__file__).name)

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

Loaded: source.py


## <font color="#CA3532">PART 1 — Phoneme binary classification</font>
 

### <font color="#CA3532">Load and inspect the dataset</font>

In [2]:
X, y = solution.load_phoneme()
overview = solution.dataset_overview(X, y)

print("Samples:", overview["samples"])
print("Features:", overview["features"])
print("Class distribution:", overview["class_distribution"])
print("First 3 rows:\n", X[:3])
print("First 10 labels:", y[:10])

# Tester checks
assert X.ndim == 2
assert y.ndim == 1
assert len(X) == len(y)
assert X.shape[1] == 5
assert set(np.unique(y)).issubset({0.0, 1.0})

Samples: 5404
Features: 5
Class distribution: {0: 3818, 1: 1586}
First 3 rows:
 [[ 1.24   0.875 -0.205 -0.078  0.067]
 [ 0.268  1.352  1.035 -0.332  0.217]
 [ 1.567  0.867  1.3    1.041  0.559]]
First 10 labels: [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


### <font color="#CA3532">Train / validation / test split and normalization</font>

**Question.** Why should a scaler be fitted only on the training set?

The validation set is used to make training decisions (e.g. early stopping). The test set is kept untouched until the final evaluation.

In [4]:
split = solution.prepare_data(
    X,
    y,
    test_size=0.20,
    val_size=0.20,
    normalize=True,
)

print("Train:", split.X_train.shape)
print("Validation:", split.X_val.shape)
print("Test:", split.X_test.shape)
print("Training feature means:", np.round(split.X_train.mean(axis=0), 3))
print("Training feature stds: ", np.round(split.X_train.std(axis=0), 3))

# Tester checks
assert split.X_train.shape[1] == X.shape[1]
assert len(split.X_train) + len(split.X_val) + len(split.X_test) == len(X)
assert split.scaler is not None
assert np.allclose(split.X_train.mean(axis=0), 0, atol=1e-5)
assert np.allclose(split.X_train.std(axis=0), 1, atol=1e-4)

Train: (3242, 5)
Validation: (1081, 5)
Test: (1081, 5)
Training feature means: [ 0. -0.  0.  0. -0.]
Training feature stds:  [1. 1. 1. 1. 1.]


### <font color="#CA3532">Baseline MLP</font>

A small MLP is enough for the learning objective. For binary classification, the final layer uses one sigmoid unit and the loss is binary cross-entropy.

In [7]:
nn = solution.build_baseline_model(
    input_dim=split.X_train.shape[1],
    hidden_units=8,
)
solution.compile_binary_model(
    nn,
    optimizer="adam",
    learning_rate=1e-3,
)

nn.summary()

# Tester checks
assert nn.output_shape[-1] == 1
assert nn.layers[-1].activation.__name__ == "sigmoid"
assert nn.loss == "binary_crossentropy"

Model: "baseline_mlp"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 8)              │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 57 (228.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

### <font color="#CA3532">Defining our model</font>

- From the input to the output in keras we can define the properties of each layer (size, activation function, connectivity topology...) with the sequential mode.

- In this case we are going to create our basic multilayer feedforward network



In [ ]:
# Define the model using keras
nn = Sequential()

#-------------------------------------------------------------------------------
# TO-DO block: Add fully connected layers to create a MLP like in assignment 1
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# End of TO-DO block
#-------------------------------------------------------------------------------

### <font color="#CA3532">Compile the network</font>

- Compile is the step where our network is created

- Here we have to define different aspects involved in the trainning of the network

- In each section you have an URL to the official documentation. Take a look at the availability of different strategies in each case.

- It is possible to also define your own functions for this.

### <font color="#CA3532"> Optimizer </font>

Strategy to calculate the weights corrections

https://keras.io/api/optimizers/


### <font color="#CA3532"> Loss function </font>

The purpose of loss functions is to compute the quantity that a model should seek to minimize during training.

https://keras.io/api/losses/

### <font color="#CA3532"> Metrics (results) </font>

A metric is a function that is used to judge the performance of your model.

Metric functions are similar to loss functions, except that the results from evaluating a metric are not used when training the model. Note that you may use any loss function as a metric.

https://keras.io/api/metrics/

In [ ]:
# Compile

#-------------------------------------------------------------------------------
# TO-DO block: Compile your network, to reproduce the assignment 1 MLP
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# End of TO-DO block
#-------------------------------------------------------------------------------

### <font color="#CA3532">Train the network</font>

The Fit method trains the network according to the data.

Here we introduce all the data together and select a 20% of the data for validation purposes.

Other ways to do this are allowed, including the optimization of the parameters.

https://keras.io/api/models/model_training_apis/#fit-method

In [ ]:
# Fit
# history = nn.fit(x, y, epochs=4, verbose=1, validation_split=0.2)

# Fit
history = nn.fit(x, y, epochs=500, verbose=0, validation_split=0.2)

In [ ]:
# Network details
nn.summary()
print('\n\n')

# Evaluate (similar to fit but just considering 1 epoch iteration without changing the network)
loss, accuracy = nn.evaluate(x, y)
print('Accuracy: %.2f' % (accuracy*100))

# Also, the predict method is available to classify unlabeled data

### <font color="#CA3532">Plot data</font>

- History object saves the different epoch data

In [ ]:
# Plot history

print(history.history.keys())

plt.plot(history.history['accuracy'], label='Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation accuracy')
plt.title('Accuracy')
plt.ylabel('')
plt.xlabel('Epoch')
plt.legend(loc="upper left")
plt.show()

plt.plot(history.history['loss'], label='Loss')
plt.plot(history.history['val_loss'], label='Validation loss')
plt.title('Mean Square Error')
plt.ylabel('')
plt.xlabel('Epoch')
plt.legend(loc="upper left")
plt.show()

In [ ]:
#-------------------------------------------------------------------------------
# TO-DO block: Explain what you observe
#-------------------------------------------------------------------------------
# Using a small number of neurons in the hidden layer (~= input layer)

# Using a big number of neurons in the hidden layer (>> input layer)

#-------------------------------------------------------------------------------
# End of TO-DO block
#-------------------------------------------------------------------------------

### <font color="#CA3532">Optimize the network design</font>

- Change the network arquitecture, introducing more layers and neurons to obtain a better result. You can:
 - Add more and different type of layers
 - Change the activation funcions
 - Change the loss / optimizer




In [ ]:
# Define the model using keras
nn = Sequential()

#-------------------------------------------------------------------------------
# TO-DO block: Include your code below
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# End of TO-DO block
#-------------------------------------------------------------------------------

# Fit
history = nn.fit(x, y, epochs=250, verbose=0, validation_split=0.2)

# Plot history

print(history.history.keys())

plt.plot(history.history['accuracy'], label='Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation accuracy')
plt.title('Accuracy')
plt.ylabel('')
plt.xlabel('Epoch')
plt.legend(loc="upper left")
plt.show()

plt.plot(history.history['loss'], label='Loss')
plt.plot(history.history['val_loss'], label='Validation loss')
plt.title('Mean Square Error')
plt.ylabel('')
plt.xlabel('Epoch')
plt.legend(loc="upper left")
plt.show()

# Network details
nn.summary()
print('\n\n')

# Evaluate (similar to fit but just 1 epoch iteration without changing the network)
loss, accuracy = nn.evaluate(x, y)
print('Accuracy: %.2f' % (accuracy*100))

# <font color="#CA3532">PART 2</font>


### <font color="#CA3532">Dataset input</font>


In [ ]:
# Load here your selected dataset considering input and output dimensions

### <font color="#CA3532">Standard choice</font>

- Evaluate the training with a standard choice of cost and activation functions, learning rate, weight initialization and network topology.
- Generate the loss and accuracy figures

In [ ]:
# Code

### <font color="#CA3532">Optimizations</font>

- Evaluate each of the following optimization methods using the same representation and the duration of the training in terms of epochs to reach a choice of error and also in terms of time taken.

 a) Regularization

 b) Dropout

 c) Stochastic gradient descent

 d) Momentum  (including Nesterov version)

 e) AdaGrad

 f) RMSProp

 g) Adam

 h) Optimize

In [ ]:
# a) Regularization

In [ ]:
# b) Dropout

In [ ]:
# c) Stochastic gradient descent

In [ ]:
# d) Momentum  (including Nesterov version)

In [ ]:
# e) AdaGrad

In [ ]:
# f) RMSProp

In [ ]:
# g) Adam

In [ ]:
#  h) Optimize

### <font color="#CA3532">Implement parallelization in Keras with the best optimization</font>






*   Run tests for GPU presence

*   Use your best implementation from the previous exercise here and compare the training time both with GPUs and without GPUs.

Comment all your results.



